import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
await page.goto('http://localhost:4173/');
await page.waitForFunction(() => window.__siege, null, { timeout: 60000 });
await page.screenshot({ path: 'screenshots/n-menu.png' });
await page.evaluate(() => { window.__siege.start('nodebuff'); window.__siege.forceInput(true); });
await page.waitForFunction(() => window.__siege.state().phase === 'fight', null, { timeout: 90000 });
await page.evaluate(() => { const s = window.__siege; s.game.botBrain.behavior = 'idle'; const p = s.player, b = s.bot; b.pos.set(p.pos.x + 0.8, p.pos.y, p.pos.z + 3); b.prevPos.copy(b.pos); s.player.health = 9; s.player.selected = 4; s.game.input.setLook(Math.PI, -0.2); });
await page.waitForTimeout(800);
await page.screenshot({ path: 'screenshots/n-hold.png' });
await page.evaluate(() => window.__siege.game.input.setLook(Math.PI, -1.5));
await page.mouse.down({ button: 'right' });
await page.waitForTimeout(150);
await page.mouse.up({ button: 'right' });
await page.waitForTimeout(350);
await page.evaluate(() => window.__siege.game.input.setLook(Math.PI, -0.6));
await page.waitForTimeout(200);
await page.screenshot({ path: 'screenshots/n-splash.png' });
console.log(JSON.stringify(await page.evaluate(() => ({ hp: window.__siege.player.health, pots: window.__siege.player.count('heal_pot'), thrown: window.__siege.player.potsThrown }))), errs);
await browser.close();
